name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      testType:
        description: 'Type of test to run'
        required: true
        default: 'regression'
        type: choice
        options:
          - sanity
          - regression

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false

    env:
      CI: true
      CI_PORTAL_BASE_URL: ${{ vars.PORTAL_BASE_URL }}
      CI_PORTAL_USERNAME: ${{ secrets.PORTAL_USERNAME }}
      CI_PORTAL_PASSWORD: ${{ secrets.PORTAL_PASSWORD }}
      CI_ENVIRONMENT: "uat"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create package-lock.json if not exists
        run: |
          if [ ! -f package-lock.json ]; then
            echo "No package-lock.json found. Creating one..."
            npm install --package-lock-only
          fi

      - name: Setup npm cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Set the PLAYWRIGHT_GREP environment variable
      - name: Set test filter
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "PLAYWRIGHT_GREP=@${{ github.event.inputs.testType }}" >> $GITHUB_ENV
          else
            echo "PLAYWRIGHT_GREP=@regression" >> $GITHUB_ENV
          fi
          echo "Set PLAYWRIGHT_GREP to $PLAYWRIGHT_GREP"

      # Run tests with the environment variable set
      - name: Run tests
        env:
          CI_PORTAL_BASE_URL: ${{ vars.PORTAL_BASE_URL }}
        run: |
          echo "Running tests with PLAYWRIGHT_GREP=$PLAYWRIGHT_GREP"
          npm run test:all:uat